#===----------------------------------------------------------------------===//
#
# This source file is part of the AWS Lambda Swift 
# VSCode extension open source project.
#
# Copyright (c) 2024, the VSCode AWS Lambda Swift extension project authors.
# Licensed under Apache License v2.0.
#
# See LICENSE.txt for license information
# See CONTRIBUTORS.txt for the list of VSCode AWS Lambda Swift project authors
#
# SPDX-License-Identifier: Apache-2.0
#
#===----------------------------------------------------------------------===//

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for {{ cookiecutter.project_name }}

Globals:
  Function:
    Timeout: 60
    CodeUri: .
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512
    Architectures:
      - {{ cookiecutter.__architecture }}

Resources:
  # Lambda function
  ScheduledTaskHandler:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        # CloudWatch Events rule to trigger the Lambda function on schedule
        RateSchedule:
          Properties:
            Enabled: true
            Schedule: rate(1 hour) # Example: Run the Lambda function every hour
          Type: Schedule 
          # You can customize the schedule expression as needed
          # See https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html
          # for more schedule expression options
    Metadata:
      BuildMethod: makefile

# Print the Lambda function ARN
Outputs:
  ScheduledTaskHandler:
    Description: "ScheduledTaskHandler Lambda Function ARN"
    Value: !GetAtt ScheduledTaskHandler.Arn