#===----------------------------------------------------------------------===//
#
# This source file is part of the AWS Lambda Swift 
# VSCode extension open source project.
#
# Copyright (c) 2024, the VSCode AWS Lambda Swift extension project authors.
# Licensed under Apache License v2.0.
#
# See LICENSE.txt for license information
# See CONTRIBUTORS.txt for the list of VSCode AWS Lambda Swift project authors
#
# SPDX-License-Identifier: Apache-2.0
#
#===----------------------------------------------------------------------===//

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for {{ cookiecutter.project_name }}

Globals:
  Function:
    Timeout: 60
    CodeUri: .
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512
    Architectures:
      - {{ cookiecutter.__architecture }}

Resources:
  # Lambda function
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        # handles all methods of the REST API
        Api:
          Type: HttpApi
    Metadata:
      BuildMethod: makefile

# print API endpoint
Outputs:
  SwiftAPIEndpoint:
    Description: "API Gateway endpoint URL for your application"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
